window.videos = [
{
  "title": "Overflow",
  "mini-info-rtg": "6.6",
  "mini-info-eps": "8",
  "status": "Completed",
  "tipe": "OVA",
  "studio": "Studio Hokiboshi",
  "sinopsis": "Kazushi Sudou adalah seorang mahasiswa yang dikunjungi oleh dua sahabat masa kecilnya, Ayane dan Kotone Shirakawa. Ketika Ayane mengetahui bahwa Kazushi tidak hanya lupa membeli pudingnya tetapi juga menggunakan losion khusus miliknya saat berendam, ia memutuskan untuk membalas dendam dan bergabung dengan Kazushi di bak mandinya bersama Kotone. Akankah Kazushi yang mesum mampu tetap acuh tak acuh terhadap mereka berdua?",
  "aired-start": "2025-07-11",
  "thumbnail": "https://i.postimg.cc/gjdxqqDq/images.jpg",
  "tanda-populer": "T",
  "direktur": "Admin",
  "season": "Musim 1",
  "genre": "Romance, Ecchi, Harem",
  "hastag": [ "Romance", "Ecchi", "Harem", "keluarga", "adik", "kakak" ],
  "eps1": "https://qu.ax/CmouR.mp4",
  "eps2": "https://qu.ax/svSUo.mp4",
  "eps3": "https://qu.ax/irnUh.mp4",
  "eps4": "https://qu.ax/Rtowg.mp4",
  "eps5": "https://qu.ax/UHsQg.mp4",
  "eps6": "https://qu.ax/TMUVR.mp4",
  "eps7": "https://qu.ax/vilBn.mp4",
  "eps8": "https://qu.ax/HqLpP.mp4"
},
  {
  "title": "Boku no Risou no Isekai Seikatsu",
  "mini-info-rtg": "6.6",
  "mini-info-eps": "1",
  "status": "Completed",
  "tipe": "OVA",
  "studio": "Studio 1st",
  "sinopsis": "Di dunia yang ditujunya, ia menjadi bocah kemonomimi. Seorang pria lajang berusia 40 tahun tanpa nama melakukan masturbasi terlalu banyak hingga kehilangan kesadaran. Ia mengira bahwa ia telah menyelesaikan hidupnya di bumi. Namun, saat ia sadar kembali, ia mendapati seorang gadis manis dengan raut wajah khawatir di hadapannya.\\nNamanya Misia, dan dia memanggil pria itu Norn.",
  "aired-start": "2025-07-10",
  "thumbnail": "https://i.postimg.cc/3NQ66DxJ/images.jpg",
  "tanda-populer": "T",
  "direktur": "Admin",
  "season": "Musim 1",
  "genre": "Fantasy, Isekai, Harem",
  "hastag": [
    "Fantasy",
    "Isekai",
    "Harem"
  ],
  "eps1": "https://qu.ax/gwNvp.mp4"
},
  {
  "title": "Kiss x Sis",
  "mini-info-rtg": "6.80",
  "mini-info-eps": "12",
  "status": "Completed",
  "tipe": "Series",
  "studio": "feel.",
  "sinopsis": "Ketika ayah Keita Suminoe menikah lagi, ia tidak hanya mendapatkan ibu baru, tetapi juga saudara kembar yang lebih tua. Berbeda tetapi serupa, Ako yang sederhana dan dewasa adalah mantan ketua OSIS, sementara Riko yang atletis dan penyendiri adalah ketua disiplin sebelumnya. Ketiganya telah bersama sejak taman kanak-kanak, yang menghasilkan ikatan yang dalam di antara kedua saudara kandung tersebut. Namun, seiring berjalannya waktu, hubungan mereka berkembang menjadi sesuatu yang lebih romantisÃ¢ÂÂdan erotis.",
  "aired-start": "2025-07-12",
  "thumbnail": "https://i.postimg.cc/L6tKKMp2/images.jpg",
  "tanda-populer": "F",
  "direktur": "Admin",
  "season": "Musim 1",
  "genre": "Comedy, Romance, Seinen, School, Harem",
  "hastag": [
    "Comedy",
    "Romance",
    "Seinen",
    "School",
    "Harem"
  ],
  "eps1": "https://qu.ax/TmnyQ.mp4",
  "eps2": "https://qu.ax/AQiNl.mp4",
  "eps3": "https://qu.ax/ROYbT.mp4",
  "eps4": "https://qu.ax/nWeUg.mp4",
  "eps5": "https://qu.ax/naNOB.mp4",
  "eps6": "https://qu.ax/jrjRk.mp4",
  "eps7": "https://qu.ax/jhrBR.mp4",
  "eps8": "https://qu.ax/SSvYG.mp4",
  "eps9": "https://qu.ax/QAZyO.mp4",
  "eps10": "https://qu.ax/iGKDG.mp4",
  "eps11": "https://qu.ax/yngpZ.mp4",
  "eps12": "https://qu.ax/xPcDl.mp4"
},
  {
  "title": "Shoujo Ramune",
  "mini-info-rtg": "6.7",
  "mini-info-eps": "5",
  "status": "Complete",
  "tipe": "OVA",
  "studio": "New Generation",
  "sinopsis": "pinggiran Tokyo. Ia telah berhenti dari pekerjaan sebelumnya untuk menjauh dari hiruk pikuk kota besar dan kini menikmati hari-harinya dikelilingi gadis-gadis kecil.",
  "aired-start": "2025-07-30",
  "thumbnail": "https://i.postimg.cc/gj2zq8xJ/Shoujo-Ramune-Episode-5.jpg",
  "tanda-populer": "true",
  "direktur": "Admin",
  "season": "Musim 1",
  "genre": "Mecha, School, Harem",
  "hastag": [
    "Mecha",
    "School",
    "Harem"
  ],
  "eps1": "https://qu.ax/wZYaX.mp4",
  "eps2": "https://qu.ax/WxulB.mp4",
  "eps3": "https://qu.ax/gZfNF.mp4",
  "eps4": "https://qu.ax/OBqVp.mp4",
  "eps5": "https://qu.ax/rkzYm.mp4"
},
  {
  "title": "Isekai Mokushiroku Mynoghra: Hametsu no Bunmei de Hajimeru Sekai Seifuku",
  "mini-info-rtg": "6.9",
  "mini-info-eps": "12",
  "status": "Complete",
  "tipe": "TV",
  "studio": "Maho Film",
  "sinopsis": "Takuto Ira meninggal karena penyakit di usia muda dan akhirnya bereinkarnasi di dunia yang menyerupai game strategi berbasis giliran fantasi Eternal Nations. Ia tidak hanya bereinkarnasi ke dalam game favoritnya, tetapi juga sebagai dewa yang memimpin peradaban jahat Mynoghra. Dengan unit pahlawan Mynoghra yang cantik, Sludge Witch Atou di sisinya, bahkan sifat ras yang sangat sulit sekalipun tidak akan menghalangi mereka untuk memulai kembali peradaban mereka!",
  "aired-start": "2025-08-12",
  "thumbnail": "https://i.postimg.cc/cLtRFQ5P/Mynoghra.jpg",
  "tanda-populer": "",
  "direktur": "Admin",
  "season": "Musim 1",
  "genre": "Adventure, Fantasy, Isekai",
  "hastag": [
    "Adventure",
    "Fantasy",
    "Isekai"
  ],
  "eps1": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F1-720p-1751809496595.mp4",
  "eps2": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F2-360p-1752414404908.mp4",
  "eps3": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F3-360p-1753018830281.mp4",
  "eps4": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F4-720p-1753623594405.mp4",
  "eps5": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F5-360p-1754228274485.mp4",
  "eps6": "https://storages.animein.net/Isekai%20Mokushiroku%20Mynoghra%3A%20Hametsu%20no%20Bunmei%20de%20Hajimeru%20Sekai%20Seifuku%2F5-360p-1754228274485.mp4",
  "eps7": "",
  "eps8": "",
  "eps9": "",
  "eps10": "",
  "eps11": "",
  "eps12": ""
}
];
